import { ThemeProvider } from "next-themes";
import './globals.css'
import { Outfit, Ovo } from "next/font/google"

const outfit = Outfit({
  subsets: ["latin"], weight:["400", "500", "600", "700"],
});

const ovo = Ovo({
  subsets: ["latin"], weight:["400"],
});

export const metadata = {
  title: "Portfolio-Amanullah Yawari",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth dark" suppressHydrationWarning>
      <body
        className={`${outfit.className} ${ovo.className} 
        antialiased leading-8 overflow-x-hidden dark:bg-black dark:text-white`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>

      </body>
    </html>
  );
}
